log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: solace_ai_connector.log
flows:
  - name: sample workflow
    components:
      - component_name: default_component_name
        component_module: broker_input
        component_config:
          broker_type: solace
          broker_url: ${SOLACE_BROKER_URL}
          broker_username: ${SOLACE_BROKER_USERNAME}
          broker_password: ${SOLACE_BROKER_PASSWORD}
          broker_vpn: ${SOLACE_BROKER_VPN}
          broker_queue_name: q5
          broker_subscriptions:
            - topic: demo/question
              qos: 1
          payload_encoding: utf-8
          payload_format: json
      - component_name: web_search
        component_module: websearch_duckduckgo
        component_config:
          engine: duckduckgo
          detail: false
        input_selection:
          source_expression: previous:payload
      - component_name: default_component_name
        component_module: broker_output
        component_config:
          broker_type: solace
          broker_url: ${SOLACE_BROKER_URL}
          broker_username: ${SOLACE_BROKER_USERNAME}
          broker_password: ${SOLACE_BROKER_PASSWORD}
          broker_vpn: ${SOLACE_BROKER_VPN}
          payload_encoding: utf-8
          payload_format: json
          copy_user_properties: true
        input_transforms:
          - type: copy
            source_expression: previous
            dest_expression: user_data.output:payload
          - type: copy
            source_expression: template:demo/response
            dest_expression: user_data.output:topic
        input_selection:
          source_expression: user_data.output
